spring:
  application:
    name: workapi

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
    connection-timeout: 3s
    socket-timeout: 30s

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  jpa:
    open-in-view: false

app:
  elasticsearch:
    post-search:
      ensure-index-on-startup: ${ELASTICSEARCH_ENSURE_POST_SEARCH_INDEX:true}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:mypros3-696254624810-ap-southeast-2-an}
    region: ${AWS_REGION:ap-southeast-2}

jwt:
  secret: 3W8i2bTUFAf+rQtb6SV01OHnNEpqlntH/wfO770lw/gm3n2onNxHNNtbik6mNux7aNlMD0jsZHzdE2mYZe8vlA==
  access-token-exp-seconds: 300 #토큰 만료 시간
  refresh-token-exp-seconds: 1209600 #리프레스 토큰 만료 시간, 재발급 주기
